export default {
  AUTH: {
    LOGIN: {
      INVALID_PHONE: 'INVALID_PHONE',
      MISSING_PHONE: 'MISSING_PHONE',
      CAPTCHA_FAIL: 'CAPTCHA_FAIL',
      BLOCKED_USER: 'BLOCKED_USER',
      INVALID_OTP: 'INVALID_OTP',
      MISSING_OTP: 'MISSING_OTP',
    },
    REGISTER: {
      INVALID_FIELD: 'INVALID FIELD',
    },
  },
  DATABASE: {
    CANCELLED: 'CANCELLED',
    INVALID_ARGUMENT: 'INVALID_ARGUMENT',
  },
  COMMON: {
    NETWORK_ERROR: 'NETWORK_ERROR',
    SERVER_ERROR: 'SERVER_ERROR',
    INTERNAL_ERROR: 'INTERNAL_ERROR',
    INVALID_REQUEST: 'INVALID_REQUEST',
  },
};
